# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild build
      run: xcodebuild clean build -workspace Pecunia.xcworkspace -scheme Pecunia # -destination "platform=iOS Simulator,name=iPhone 11 Pro"
    - name: Github Release
      uses: elgohr/Github-Release-Action@v3.1
      with:
        # The name of the release to publish
        release: Pecunia
